name: kahf_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1
  
dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.8
  html: ^0.15.6
  intl: ^0.20.2
  cached_network_image: ^3.4.1
  flutter_svg: ^2.2.0

  # State Management
  flutter_riverpod: ^2.6.1

  # Navigation
  go_router: ^16.0.0

  # Cache
  shared_preferences: ^2.5.3
  hive: ^2.2.3

  # Generator
  riverpod_annotation: ^2.6.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  
  # Log
  logger: ^2.6.0
  pretty_dio_logger: ^1.4.0
  
  # Network
  dio: ^5.8.0+1
  retrofit: ^4.5.0

  # Video Player
  better_player_plus: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  riverpod_lint: ^2.6.5

  build_runner: ^2.5.4
  riverpod_generator: ^2.6.5
  retrofit_generator: ^9.2.0
  json_serializable: ^6.9.5
  freezed: ^3.1.0
  
flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/svg/